### ISSUE TITLE
Design Spec

### ISSUE THREAD

**Issue by josephgupkim** [ollygreen/dasmotos-arts-crafts-codecademy#3]
Your project looks nearly identical to the design spec which means you were able to apply the desired styling to the necessary elements. Great job on the replication!

**Comment by ollygreen** [comment]
OK thanks, I'm curious to know where the deviation was. Thanks.

**Comment by ollygreen** [comment]
Hi Joseph, waiting for a reply.

**Comment by josephgupkim** [comment]
If you're asking for the deviation based on the words "nearly identical", don't take it too seriously. It IS identical to the design spec. Good job!
