### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [ollygreen/dasmotos-arts-crafts-codecademy#4]
Awesome work on this first project as your Dasmoto was looking beautiful on both the code side and the visual web side.

- Consistent with indentations and whitespace.
- Relative paths over absolute paths.
- Accurate to design spec.

Overall, superb job! Keep it up!
Grade: Meets expectation.

**Comment by ollygreen** [comment]
OK thanks Joseph. There was one doubt I had, I was not able to add the background image as a relative path to the local file in the CSS, only as path to aws file. I troubleshooted but was not able to figure out why. I wanted to add as relative path to local file to be consistent with the other images added in the html.

**Comment by josephgupkim** [comment]
The attribute you'll want in your stylesheet to retrieve the background image is:
"background-image: url(../images/pattern.jpeg);"

Hope this helps!

**Comment by ollygreen** [comment]
got it. Thanks
